### PR TITLE
Cluster issue #38

### PR DESCRIPTION
**Pull request by ClusterH**
issue #38

### CODE REVIEW

**Comment by raiseandfall** [comment]
@ClusterH Awesome thank you sir
@Wondermarin I know you are working on v7, but would appreciate a lot if you could merge that one in. :raised_hands:

**Comment by ClusterH** [comment]
I'd really appreciate it if we could see a new version soon :)

**Comment by raiseandfall** [comment]
What would it take to get this one merged and a minor update released? I have a project that could really use it very soon.

**Comment by Wondermarin** [comment]
@raiseandfall
As for this PR: the same functionality was implemented before version [6.2.0](https://github.com/Wondermarin/react-color-palette/releases/tag/v6.2.0) and was removed, because it caused an [infinite re-render of React](https://github.com/Wondermarin/react-color-palette/pull/26) when using RGB/HSV models. I have a solution to this problem and will definitely publish it in the next version.

P.S. I understand that you want to use the new version as soon as possible. But now I have very little time to develop this project. I will do my best to release version 7.0.0 with many fixes and improvements in June, but I can't promise.

**Comment by raiseandfall** [comment]
@Wondermarin thank you for the updates, I totally understand. I'm in the same position on other OS projects. I think I might have to look into other solutions for the time being, so don't feel like rushing anything.

**Comment by Wondermarin** [comment]
Added in v7

**Pull request closed without merging**
